name: Lint Code Base and Docker Build

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint # Ова значи дека Docker чекорот ќе се стартува само ако lint чекорот помине успешно

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ivanoskif/kiii-github-actions-hw:latest .
        
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ivanoskif/kiii-github-actions-hw:latest
